### 
# @name create-dashboard
POST http://localhost:8080/dashboard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjczZTBkOTkyNmM1ZWM2ZDY2OTAzYWZmIiwiaWF0IjoxNzMyMTIwMDEzLCJleHAiOjE3MzIxMjYwMTN9.nuRZqMHhGO2hm_0rybZISlILkcMnEHEF1-4bvcUvbG0

{
  "items": [
    {
      "name": "test2",
      "url": "https://www.google.com",
      "color": "#bbccee",
      "icon": "GoogleIcon",
      "positions": [
        [
            7,
            7
        ]
      ] 
    }
  ]
}

### 
# @name create-item-in-dashboard
POST http://localhost:8080/dashboard/673e10afdc36087c84bf72e6/item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjczZTBkOTkyNmM1ZWM2ZDY2OTAzYWZmIiwiaWF0IjoxNzMyMTIwMDEzLCJleHAiOjE3MzIxMjYwMTN9.nuRZqMHhGO2hm_0rybZISlILkcMnEHEF1-4bvcUvbG0

{
  "name": "facebook",
  "url": "https://www.facebook.com",
  "color": "#aa12ab",
  "icon": "FacebookIcon",
  "positions": [
    [
        2,
        2
    ],
    [
        3,
        2
    ]
  ] 
}


### 
# @name get-users
GET http://localhost:8080/users

### 
# @name get-dashboards
GET http://localhost:8080/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiNjczYjMxMWUwMTllZTQxMjY5MTQwZmY1IiwiaWF0IjoxNzMyMDIyMDA5LCJleHAiOjE3MzIwMjgwMDl9.wH9KtY6z42X_VAPUvEDlzSsq94dCri_75pw3hguXX1Q

### 
# @name create-user
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOiI2NzNhMWNlYzNlMGM3YmIxMzE4NjE3YzMiLCJpYXQiOjE3MzE4NjQ4MTEsImV4cCI6MTczMTg2NDg3MX0.5MnIvePGTxRYvED8qFZxG6C5ZaWANpzBbNtGJL57Ukc

### 
# @name login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

