### 
# @name create-dashboard
POST http://localhost:8080/dashboard
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOiI2NzNhMWNlYzNlMGM3YmIxMzE4NjE3YzMiLCJpYXQiOjE3MzE4NjQyNzUsImV4cCI6MTczMTg2NDMzNX0.GX3moIh4eUOUsnhRSIoY-JP4qOE_SsQB4aei-WJBSNs


### 
# @name get-users
GET http://localhost:8080/users

### 
# @name get-dashboards
GET http://localhost:8080/dashboard

### 
# @name create-dashboard
POST http://localhost:8080/dashboard/6738ee9365392db08274ff8c/item/6738ee9365392db08274ff8a/positions
Content-Type: application/json

{
  "positions": [ [1,2], [2,2]]
}


### 
# @name create-user
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJzdWIiOiI2NzNhMWNlYzNlMGM3YmIxMzE4NjE3YzMiLCJpYXQiOjE3MzE4NjQ4MTEsImV4cCI6MTczMTg2NDg3MX0.5MnIvePGTxRYvED8qFZxG6C5ZaWANpzBbNtGJL57Ukc

### 
# @name login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

